### ISSUE TITLE
Why the QuDiffEq can not be precomplied?

### ISSUE THREAD

**Issue by LinhanJi** [QuantumBFS/QuDiffEq.jl#30]
ERROR: LoadError: Failed to precompile QuDiffEq [c02438fe-7edc-11e9-0a49-b5c5aafabe04] to C:\Users\35321\.juliapro\JuliaPro_v1.4.2-1\compiled\v1.4\QuDiffEq\hei7O_TPJID.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1272
 [3] _require(::Base.PkgId) at .\loading.jl:1029
 [4] require(::Base.PkgId) at .\loading.jl:927
 [5] require(::Module, ::Symbol) at .\loading.jl:922

**Comment by Roger-luo** [comment]
Hi sorry, due to lack of human power, this package is not actively maintained currently.

**Comment by Roger-luo** [comment]
we had several updates in Yao, I believe this package only works with Yao@0.4, you will need to checkout to this commit to use it: https://github.com/QuantumBFS/QuDiffEq.jl/tree/3b189e583065bd8c337f1c88b4a1d2edb5835c52

**Comment by LinhanJi** [comment]
Oh,Thank you!I will try it again now.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QuantumBFS/QuDiffEq.jl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 下午3:34
收件人:&nbsp;"QuantumBFS/QuDiffEq.jl"<QuDiffEq.jl@noreply.github.com&gt;;
抄送:&nbsp;"LinhanJi_donglab"<jlh_donglab_45@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [QuantumBFS/QuDiffEq.jl] Why the QuDiffEq can not be precomplied? (#30)





 
we had several updates in Yao, I believe this package only works with Yao@0.4, you will need to checkout to this commit to use it: https://github.com/QuantumBFS/QuDiffEq.jl/tree/3b189e583065bd8c337f1c88b4a1d2edb5835c52

**Comment by LinhanJi** [comment]
How can I change to Yao@0.4?I don’t quite understand, it's my first contact to it




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QuantumBFS/QuDiffEq.jl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 下午3:34
收件人:&nbsp;"QuantumBFS/QuDiffEq.jl"<QuDiffEq.jl@noreply.github.com&gt;;
抄送:&nbsp;"LinhanJi_donglab"<jlh_donglab_45@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [QuantumBFS/QuDiffEq.jl] Why the QuDiffEq can not be precomplied? (#30)





 
we had several updates in Yao, I believe this package only works with Yao@0.4, you will need to checkout to this commit to use it: https://github.com/QuantumBFS/QuDiffEq.jl/tree/3b189e583065bd8c337f1c88b4a1d2edb5835c52

**Comment by Roger-luo** [comment]
```
]add Yao@0.4
```

**Comment by LinhanJi** [comment]
add Yao@0.4
&nbsp; Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Yao [5872b779]:
&nbsp;Yao [5872b779] log:
&nbsp;├─possible versions are: [0.1.4, 0.2.0-0.2.2, 0.3.0-0.3.2, 0.4.0-0.4.2, 0.5.0-0.5.1, 0.6.0-0.6.3] or uninstalled
&nbsp;├─restricted to versions 0.6 by QuDiffEq [c02438fe], leaving only versions 0.6.0-0.6.3
&nbsp;│ └─QuDiffEq [c02438fe] log:
&nbsp;│&nbsp; &nbsp;├─possible versions are: 0.1.0 or uninstalled
&nbsp;│&nbsp; &nbsp;└─QuDiffEq [c02438fe] is fixed to version 0.1.0
&nbsp;└─restricted to versions 0.4 by an explicit requirement — no versions left


(@v1.4) pkg&gt; add Yao@0.4.0
&nbsp; Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Yao [5872b779]:
&nbsp;Yao [5872b779] log:
&nbsp;├─possible versions are: [0.1.4, 0.2.0-0.2.2, 0.3.0-0.3.2, 0.4.0-0.4.2, 0.5.0-0.5.1, 0.6.0-0.6.3] or uninstalled
&nbsp;├─restricted to versions 0.6 by QuDiffEq [c02438fe], leaving only versions 0.6.0-0.6.3
&nbsp;│ └─QuDiffEq [c02438fe] log:
&nbsp;│&nbsp; &nbsp;├─possible versions are: 0.1.0 or uninstalled
&nbsp;│&nbsp; &nbsp;└─QuDiffEq [c02438fe] is fixed to version 0.1.0
&nbsp;└─restricted to versions 0.4.0 by an explicit requirement — no versions left

Sorry,it is wrong




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QuantumBFS/QuDiffEq.jl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 下午3:58
收件人:&nbsp;"QuantumBFS/QuDiffEq.jl"<QuDiffEq.jl@noreply.github.com&gt;;
抄送:&nbsp;"LinhanJi_donglab"<jlh_donglab_45@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [QuantumBFS/QuDiffEq.jl] Why the QuDiffEq can not be precomplied? (#30)





 ]add Yao@0.4

**Comment by Roger-luo** [comment]
You need to `git clone` QuDiffEq first. 

```
git clone https://github.com/QuantumBFS/QuDiffEq.jl.git QuDiffEq
```

then checkout to that commit

```
cd QuDiffEq
git checkout 3b189e583065bd8c337f1c88b4a1d2edb5835c52
```

**Comment by Roger-luo** [comment]
or just add this package via

```
] rm QuDiffEq
] add Yao@0.4.0
]add https://github.com/QuantumBFS/QuDiffEq.jl.git#3b189e583065bd8c337f1c88b4a1d2edb5835c52
```

You need to remove the incompatible version first.

**Comment by LinhanJi** [comment]
(v1.0) pkg&gt; add https://github.com/QuantumBFS/QuDiffEq.jl.git#3b189e583065bd8c337f1c88b4a1d2edb5835c52
&nbsp; &nbsp;Cloning git-repo `https://github.com/QuantumBFS/QuDiffEq.jl.git`
ERROR: failed to clone from https://github.com/QuantumBFS/QuDiffEq.jl.git, error: GitError(Code:ERROR, Class:Net, malformed URL 'http://127.0.0.1:1080;DIRECT')


(v1.0) pkg&gt;&nbsp; rm QuDiffEq
┌ Warning: `QuDiffEq` not in project, ignoring
└ @ Pkg.Operations C:\Users\julia\AppData\Local\Julia-1.0.5\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1194
[ Info: No changes

It is wrong again...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QuantumBFS/QuDiffEq.jl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 下午4:11
收件人:&nbsp;"QuantumBFS/QuDiffEq.jl"<QuDiffEq.jl@noreply.github.com&gt;;
抄送:&nbsp;"LinhanJi_donglab"<jlh_donglab_45@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [QuantumBFS/QuDiffEq.jl] Why the QuDiffEq can not be precomplied? (#30)





 
or just add this package via
 ] rm QuDiffEq ] add Yao@0.4.0 ]add https://github.com/QuantumBFS/QuDiffEq.jl.git#3b189e583065bd8c337f1c88b4a1d2edb5835c52  
You need to remove the incompatible version first.

**Comment by LinhanJi** [comment]
Now it change to....
Failed to precompile Yao


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QuantumBFS/QuDiffEq.jl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 下午4:11
收件人:&nbsp;"QuantumBFS/QuDiffEq.jl"<QuDiffEq.jl@noreply.github.com&gt;;
抄送:&nbsp;"LinhanJi_donglab"<jlh_donglab_45@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [QuantumBFS/QuDiffEq.jl] Why the QuDiffEq can not be precomplied? (#30)





 
or just add this package via
 ] rm QuDiffEq ] add Yao@0.4.0 ]add https://github.com/QuantumBFS/QuDiffEq.jl.git#3b189e583065bd8c337f1c88b4a1d2edb5835c52  
You need to remove the incompatible version first.

**Comment by Roger-luo** [comment]
can you just remove everything you have installed, then `add Yao@0.4`? Or just use a clean new environment to install this.

**Comment by LinhanJi** [comment]
I have removed all,and reinstall again.Here is my operation and Julia version.
Julia 1.4.2&nbsp; &nbsp; juliapro 1.4.2
add Yao@0.4.0
add https://github.com/QuantumBFS/QuDiffEq.jl.git#3b189e583065bd8c337f1c88b4a1d2edb5835c52


and it is wrong.Error:1.DefaultRegister not defined;2.&nbsp;Failed to precompile QuDiffEq
And another operation:
add Yao
add&nbsp;https://github.com/QuantumBFS/QuDiffEq.jl.git
it is wrong again.The same Error 




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QuantumBFS/QuDiffEq.jl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月8日(星期六) 凌晨5:24
收件人:&nbsp;"QuantumBFS/QuDiffEq.jl"<QuDiffEq.jl@noreply.github.com&gt;;
抄送:&nbsp;"LinhanJi_donglab"<jlh_donglab_45@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [QuantumBFS/QuDiffEq.jl] Why the QuDiffEq can not be precomplied? (#30)





 
can you just remove everything you have installed, then add Yao@0.4? Or just use a clean new environment to install this.

**Comment by LinhanJi** [comment]
sorry..I try again now.It is not appear "Failed to precomplied',but&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "QuantumBFS/QuDiffEq.jl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月8日(星期六) 凌晨5:24
收件人:&nbsp;"QuantumBFS/QuDiffEq.jl"<QuDiffEq.jl@noreply.github.com&gt;;
抄送:&nbsp;"LinhanJi_donglab"<jlh_donglab_45@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [QuantumBFS/QuDiffEq.jl] Why the QuDiffEq can not be precomplied? (#30)





 
can you just remove everything you have installed, then add Yao@0.4? Or just use a clean new environment to install this.

**Comment by LinhanJi** [comment]
orry..I try again now.It is not appear "Failed to precomplied",but 
[ Info: Precompiling QuDiffEq [c02438fe-7edc-11e9-0a49-b5c5aafabe04]
┌ **Warning:** Module Yao with build ID 160534696329001 is missing from the cache.
│ This may mean Yao [5872b779-8223-5990-8dd0-5abbb0748c8c] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1016
[ Info: Skipping precompilation since __precompile__(false). Importing QuDiffEq [c02438fe-7edc-11e9-0a49-b5c5aafabe04].
ERROR: LoadError: LoadError: LoadError: **UndefVarError: DefaultRegister not defined
Stacktrace:**

**Comment by Roger-luo** [comment]
We will update this repo after YaoLang is done. I'll leave this repo open for now.

**Comment by dgan181** [comment]
@Roger-luo , I was wondering if you can help me close this issue.

**Comment by dgan181** [comment]
#31 fixes precompilation

**Comment by dgan181** [comment]
@Roger-luo  We can close this issue now.
